googleapis/code-suggester

system-test/main.test.ts

Added `system-test directory` with a test file so kokoro runs
Fixes #46

chore: initialize system tests

---

synth.py

We have automated tooling that will overwrite the README every day if we don't add an exclude rule for it.
see: #50

build: do not overwrite hand-written README.md

---

README.md
package.json
src/bin/code-suggester.ts
src/bin/handle-git-dir-change.ts
src/bin/workflow.ts
test/cli.ts
test/fixtures/fixtures
test/git-dir-handler.ts

Create a CLI interface to interact with the framework-core
It:
- takes arguments and maps them to user PR options
- takes a git directory and generates a change set Map from the git diff items
- initializes octokit and a logger
- invokes framework-core
- includes core-logic testing
Closes #35 
Redo of #51

feat(cli): cli interface

---

src/github-handler/branch-handler.ts
src/github-handler/commit-and-push-handler.ts
src/index.ts
test/branch.ts
test/commit-and-push.ts
test/main-make-pr.ts

Behaviour: when a change set is given, a commit is created with the change set applied on top of the latest upstream remote primary branch. If there is an existing branch diverging in commit history, it will be erased.
Also, if a branch exists already, no need to create a new branch.
Always return the latest upstream master sha to base future commits off of.
Towards #17

feat(git): allow force-push

---

package.json

Remove the namespace of the command from `@google-cloud/code-suggester` to `code-suggester`
Rename the bin command from `code-suggest` to `code-suggester`

fix: command and public package alias

---

entrypoint.sh
src/bin/code-suggester.ts

**Assumptions**: To my knowledge, in order to get a step to fail, the process exit code has to be 1: https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions
**Scenario:**
Currently when the node process fails, it always exits with code 0.
Tested by running local script:
```
if code-suggester pr \
--upstream-repo="dne" \
--upstream-owner="TomKristie" \
--description="describe" \
--title="title" \
--branch="something" \
--primary="master" \
--message="some message" \
--git-dir="./kubernetes"; then
exit 0
else
echo "failure exit code non-zero"
exit 1
fi
```
which tries to fork a non-existent repo.
The output is
```
{"level":30,"time":1597342089072,"pid":8411,"hostname":"penguin","msg":"Starting GitHub PR workflow..."} …
```

fix(cli,action): when process fails, make exit code 1

---

src/github-handler/comment-handler/github-patch-format-handler.ts
src/github-handler/comment-handler/remote-patch-ranges-handler.ts
src/types/index.ts
test/github-regex-patch.ts
test/remote-github-patch-text.ts

In order to suggest lines to comment on in a PR, code-suggester needs to know what lines are in-scope. If a line is suggested that does not appear in the PR file hunk, GitHub throws an error. Therefore we will need know each file's patch range for the updated content.
Hence, fetch the remote pull request so that each file's updated patch range is collected: the valid patch ranges.
Some files will not have a patch field returned, usually because the file is too large: invalid files. This is a subset of the total invalid files of that PR. Collect these files as well for future use.
Towards #59

fix(framework-core): core-library get remote patch ranges

---

package.json
src/github-handler/pull-request-handler.ts
src/index.ts
test/pr.ts

This allows upstream users of `code-suggester` to take action based on the PR number created.
release-please uses this when identifying PRs that should be closed.

feat: return the PR created

---

src/index.ts

This is required upstream by release-please.

feat(types): make "Changes" type public

---

src/index.ts
src/logger/index.ts

Allow pino to be configured with an options object, rather than requiring that upstream libraries pass in an instantiated logger instance.

feat(logging): allow pino to be configured

---

README.md
src/index.ts
src/types/index.ts
test/main-make-pr.ts

If you are using `secrets.GITHUB_TOKEN` or an application JWT, there's no associated GitHub account to fork to.
This feature adds the option to skip forking in these contexts.

feat: make forking functionality optional

---

Dockerfile
action.yaml

You should use the code-suggester library at the tagged version of the action rather than whatever is the latest stable version on npm.

refactor(action): compile action from current checkout

---

README.md
src/github-handler/comment-handler/index.ts
src/github-handler/comment-handler/make-review-handler/upload-comments-handler.ts
src/github-handler/comment-handler/raw-patch-handler/hunk-to-patch-handler.ts
src/github-handler/comment-handler/raw-patch-handler/in-scope-hunks-handler.ts
src/github-handler/comment-handler/raw-patch-handler/index.ts
src/github-handler/comment-handler/raw-patch-handler/raw-hunk-handler.ts
src/index.ts
src/types/index.ts
test/helper-review-pull-request.ts
test/hunk-to-patch.ts
test/inline-suggest.ts
test/main-review-pull-request.ts
test/suggestion-hunk.ts
test/suggestion-patch.ts

Renamed user input for text file content of 'diffs' `rawChanges` to `diffContents`.
Renamed variable name references to this user diff file contents as well, i.e. `testRawContents` -> `testDiffContents`
Renamed `RawContents` object to `FileDiffContents`
Changed return type from void to returning the review number, or null if there was no exception but a review was not created. More succinctly, the return type is `number` and `null`. `null` was chosen since it clearly indicates the "lack-of-existance" of a review.
Moved the logging of successful review into the callee since the `reviewPullRequest` caller method does not always return a number. Having the successful log directly after the corresponding async call was made rather than in the caller allows for better logging control. Now the …

feat(framework-core): return review number and variable renaming

---

src/github-handler/comment-handler/make-review-handler/upload-comments-handler.ts
test/inline-suggest.ts

fix: handle single line comments and add newline

---

src/bin/handle-git-dir-change.ts
test/git-dir-handler.ts

build(to be reverted): add logging for flaky test continuous

---

package.json
src/bin/handle-git-dir-change.ts
test/git-dir-handler.ts

This PR deletes the failing test in #154, and refactors the test suite. 
If I'm understanding this test correctly, I think this test is expecting a result that is different from what path.resolve() in Node does.
This test expects that, for path `foo/bar/hello/hi`, if given `process.cwd()` and `../hello/hi` when called from `bar`, it will get `foo/bar/hello/hi`, when in reality it should (correctly) return `foo/hello/hi`.
Given that there haven't been bugs reported, I don't think that the repo's functionality depends on getting an absolute path using `../`, but it should be worth looking out for.
I also think that this whole test suite `describe('Path resolving')` is probably not doing much for testing, given that the function it is checking against is just a wrapper for path.resolve. …

build: remove failing test and refactor test suite

---

action.yaml

I forgot to add `labels` to the GitHub Action config in #173.

fix: add labels to action.yaml

---

package-lock.json
package.json
src/github-handler/fork-handler.ts
test/branch.ts
test/commit-and-push.ts
test/fork.ts
test/inline-suggest.ts
test/issues.ts
test/pr.ts
test/pull-request-hunks.ts
test/remote-github-patch-text.ts

While trying to debug the thing I ran into in #180, I tried updating to the latest octokit.  That broke the build due to typing changes.

fix(deps): update to the latest version of octokit

---

renovate.json

With lock files checked into the repo, issues like the one in #181 will pop up unless we use lock file update PRs to let us know it's happening.  This updates the renovate config to give us a weekly lock file update, as well as removing some cruft with linter configs we don't need.

chore: enable renovate lock file updates

---

package-lock.json
package.json
src/bin/handle-git-dir-change.ts
src/index.ts
src/logger.ts
src/types.ts
test/util.ts

This changes the logger option provided to `reviewPullRequest()` and `createPullRequest()` to be a custom `Logger` interface that `code-suggester` declares:
```ts
interface LogFn {
/* eslint-disable @typescript-eslint/no-explicit-any */
<T extends object>(obj: T, msg?: string, ...args: any[]): void;
(msg: string, ...args: any[]): void;
/* eslint-enable @typescript-eslint/no-explicit-any */
}
export interface Logger {
error: LogFn;
warn: LogFn;
info: LogFn;
debug: LogFn;
trace: LogFn;
}
```
* This logger interface can be fulfilled by a default `Pino` logger as well as plain old `console`.
* We now default the logger to a null implementation to keep output to a minimum while allowing for a custom logger if you want output.
* We can drop the `pino` dependency as we now provide a null default …

feat!: cleanup custom logging

---

package-lock.json
test/branch.ts

The tests in #215 were failing, and this looks to fix things.  This is purposefully moving from `import` to `require` to loosen the type restrictions in the tests.

chore(deps): update to latest lock files

---

src/bin/workflow.ts
src/index.ts
src/types.ts
test/cli.ts

Options should be made as optional object properties rather than positional arguments.

refactor!: move custom logger configuration into options

---

src/bin/workflow.ts

The unawaited async call causes the method to not throw, thus we always were returning a `0` exit status.
Fixes #259

fix(cli,action): fix unawaited async call

---

src/index.ts

When forking, the forked repo is often way out of sync with its upstream repo. When using `fork`, we should attempt to sync the branch.
Fixes #335

fix: try to merge the upstream repo branch on the fork

---

src/bin/handle-git-dir-change.ts

code-suggester CLI is trying to parse an empty string as a valid file diff and crashing.
Fixes #229

fix(cli): don't crash when there are no changes

---

.github/sync-repo-settings.yaml
.github/workflows/ci-action.yaml
.github/workflows/ci.yaml
action.yaml
action/package-lock.json
action/package.json
package-lock.json
package.json

New octokit versions also drop node 12
build!: drop Node 12 support
build(action)!: upgrade to Node 14

deps!: update @octokit/rest to v19

---

src/bin/code-suggester.ts
src/bin/workflow.ts
src/default-options-handler.ts
src/github/commit-and-push.ts
src/github/create-commit.ts
src/index.ts
src/types.ts
test/cli.ts
test/commit-and-push.ts
test/main-pr-option-defaults.ts

Provides a new option for `filesPerCommit` which defaults to 100. If there are more than this limit, `code-suggester` will split into groups of files and make multiple commits. For most use cases, this is a no-op. For larger monorepos, you may see multiple commits.
Fixes #397 
Ran the following command:
```
node build/src/bin/code-suggester.js pr -r code-suggester -o googleapis -t 'testing multiple commits' -d 'testing multiple commits description' -m 'testing multiple commits body' --branch=test-branch --fork=false -f --files-per-commit=3 --git-dir=.
```
with a few test files in my working directory to create: https://github.com/googleapis/code-suggester/pull/401 which has multiple commits.

feat: group commit files into batches

---

package-lock.json
src/errors.ts
src/github/commit-and-push.ts
src/github/create-commit.ts
src/index.ts
test/commit-and-push.ts

Towards https://github.com/googleapis/repo-automation-bots/issues/4537
This will allow us to handle this particular class of errors (likely log a warning and ignore). It's easier for us to classify these errors as we throw them rather than trying to get the caller to distinguish which portion of the call to `createPullRequest` failed.

feat: throw new CommitError if an API error occurs during commit process

---

.jsdoc.js
package-lock.json
package.json

Remove dependency on jsdoc-fresh which uses taffydb.

deps: remove jsdoc-fresh devDependency
