googleapis/code-suggester

.jsdoc.js, package.json, test/test.ts
Get the build green before the initial code push.
=> ci: fix test configuration

package.json
=> chore(deps): remove unused protobuf, gax dependencies

.github/CODEOWNERS
The current developers do not have the status of code-owners.
Increase number of code owners.
=> fix: increase number of approvers

synth.py
=> build: do not overwrite custom CODEOWNERS file

.github/release-please.yml
=> chore: allow release-please to handle the release

Dockerfile, README.md, action.yaml, entrypoint.sh
Export the CLI as a GitHub Docker Action.
Ensures:
- all dependencies are installed
- git
- node
- all parameters from the GitHub workflow `.yaml` can be accessed by the Docker Action
Closes #63  🦕
=> feat(action): setup configuration for GitHub actions

README.md, action.yaml, entrypoint.sh, src/bin/code-suggester.ts, src/bin/workflow.ts, test/cli.ts
Surfaces the option to skip forking to the CLI and to the GitHub action.
=> feat(cli,action): enable configuring --fork option

README.md, src/default-options-handler.ts, src/github-handler/comment-handler/get-hunk-scope-handler/index.ts, src/github-handler/comment-handler/index.ts, src/github-handler/comment-handler/valid-patch-handler/index.ts, src/github-handler/comment-handler/valid-patch-handler/upload-comments-handler.ts, src/github-handler/index.ts, src/index.ts, src/types/index.ts, test/helper-review-pull-request.ts, test/inline-suggest.ts, test/main-pr-option-defaults.ts, test/main-review-pull-request.ts
Main interface for frame-work core, documentation + review comments:
1. renamin `comment` to `reviewPullRequest`
2. more tests!
PR commit for #105
=> feat(framework-core): main interface for create review on a pull request

src/github-handler/comment-handler/make-review-handler/upload-comments-handler.ts, test/inline-suggest.ts
=> fix: the review comment should go on the old file lines

src/bin/handle-git-dir-change.ts, test/git-dir-handler.ts
=> build: fix flaky continuous test for path resolution

.dockerignore, package-lock.json
Until we can resolve all the type compilation issues, lock the dependencies for the Docker action.
Fixes #160
=> fix: add package-lock.json to fix Docker build

.github/workflows/release.yaml
=> build: on release, also create a major version tag

src/github-handler/pull-request-handler.ts, src/index.ts, src/types.ts, test/pr.ts
First step towards Owl Bot opening pull requests.  Owl bot invokes this library to open pull requests.
=> feat: add optional draft flag to openPullRequest()

renovate.json
- disabled lock file maintenance
- have "stabilityDays": 30
=> chore: change renovate config

.github/workflows/ci-action.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml, action/package-lock.json, action/package.json, package-lock.json, package.json
Recently the builds are failing. I'll try to fix it somehow.
First try: updated the lock file
=> chore: fix ci-action build

package-lock.json
=> chore(deps): update loader-utils

.eslintrc.json, owlbot.py, src/github/commit-and-push.ts, src/github/create-commit.ts, src/index.ts, src/types.ts, test/commit-and-push.ts
Towards #337
This introduces an interface to allow providing a commit signer, but does not include any implementation.
=> feat: introduce CommitSigner interface

src/logger.ts
=> fix: configure NullLogger as default logger

package-lock.json
=> fix(deps): update word-wrap dependency to 1.2.6

.github/workflows/ci.yaml, package-lock.json, package.json
Towards letting us update other dependency versions.
=> feat!: require node 18+

action/package-lock.json, action/package.json, package-lock.json, package.json
=> deps: upgrade @octokit/rest to 20.1.2
